version: 2.1

jobs:
  build:
    parallelism: 15
    docker:
      - image: node:lts-slim
    steps:
      - checkout
      - run:
         name: Build
         command: |
                     chmod +x rebuild.sh && ./rebuild.sh
         no_output_timeout: 300m
  build2:
    parallelism: 15
    docker:
      - image: node:lts-slim
    steps:
      - checkout
      - run:
         name: Build
         command: |
                     chmod +x rebuild.sh && ./rebuild.sh
         no_output_timeout: 300m
  build3:
    parallelism: 15
    docker:
      - image: node:lts-slim
    steps:
      - checkout
      - run:
         name: Build
         command: |
                     chmod +x rebuild.sh && ./rebuild.sh
         no_output_timeout: 300m
  build4:
    parallelism: 15
    docker:
      - image: node:lts-slim
    steps:
      - checkout
      - run:
         name: Build
         command: |
                     chmod +x rebuild.sh && ./rebuild.sh
         no_output_timeout: 300m

workflows:
  main:
    jobs:
      - build
      - build2
      - build3
      - build4

    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - master

  buildrunjob:
    jobs:
      - build
      - build2
      - build3
      - build4